Security
AHL-Logics-backend-tranining-2024/Final-Project---Team-3 pull request #6
Opened 2024-10-14 15:50 UTC by yassersh12

This PR introduces the main components for authentication and authorization:
Changes
auth.py:
Handles JWT token generation, validation, and user extraction.
Includes dependencies for user and admin validation.
Password Utility:
Adds secure password hashing and verification using Passlib.
Login Endpoint:
Implements /login with OAuth2PasswordRequestForm.
Uses a fake in-memory database for testing, returning a 30-minute JWT token on success.

The next PR will integrate these components with the real database.

2024-10-14 16:05 UTC, Omarjabari007 approved these changes
Hey, Yasser (Approaved by omar) , We gonna merge the new changes from ur security to my updated user model tmr .

2024-10-15 06:56 UTC, FaresAbuIram requested changes
Please try always to make a shorter PR

2024-10-15 06:56 UTC, FaresAbuIram commented on .github/CODEOWNERS
Don't change this file at all

2024-10-15 06:56 UTC, FaresAbuIram commented on app/api/dependencies/auth.py
> +SECRET_KEY = "14023cf09525c115172ca54db97fb5d3046a88119afd490bc4db34a061a06be5"
Move it with next two lines to the environment variable file

2024-10-15 06:56 UTC, FaresAbuIram commented on app/api/dependencies/auth.py
> +def authenticate_user(username: str, password: str):
Please use try except

2024-10-15 06:56 UTC, FaresAbuIram commented on app/api/dependencies/auth.py
> +def create_access_token(data: dict, expires_delta: timedelta | None = None):
Use try except

2024-10-15 06:56 UTC, FaresAbuIram commented on app/api/dependencies/auth.py
> +    if current_user.disabled:
I think the attribute name is active not disabled

2024-10-15 06:56 UTC, FaresAbuIram commented on app/api/routes/login.py
> +def create_admin_user(user: User):
Register is for normal user, so the function name is not accurate. 
If we need to change that to admin,.we have another endpoint for that called change role.

And you need to check if the email is already registered

2024-10-15 06:56 UTC, FaresAbuIram commented on app/models.py
> +    price: Decimal = Field(..., description="Product Price !  ")
Add the validation here, it shouldn't be a negative number

2024-10-15 06:56 UTC, FaresAbuIram commented on app/models.py
> +    stock: Optional[int] = Field(None, description="Stock Quantity ")
Add stock validation here

2024-10-15 06:56 UTC, FaresAbuIram commented on app/models.py
> +    @validator("price")
It's easier to add the validation directly since it's not a complex validation

2024-10-15 06:56 UTC, FaresAbuIram commented on app/api/services/product_service.py
> +    def create_product(self, product: Product) -> Product:
The product name is unique

2024-10-15 06:56 UTC, FaresAbuIram commented on app/api/services/product_service.py
> +    def update_product(
The product name is unique

2024-10-15 06:56 UTC, FaresAbuIram commented on app/api/routes/user.py
> +    validate_password(user.hashed_password)
hashed_password here is confusing since the password is not hashed yet

2024-10-15 06:56 UTC, FaresAbuIram commented on app/api/routes/user.py
> +    user.hashed_password = pwd_context.hash(user.hashed_password)
You already have a hash_password method inside the user service

2024-10-15 06:56 UTC, FaresAbuIram commented on app/api/routes/user.py
> +    user = user_service.get_user(user_id)
Stop user(not admin) to see others' account

2024-10-15 06:56 UTC, FaresAbuIram commented on app/api/routes/user.py
> +def get_all_users():
Only for admin

2024-10-15 06:56 UTC, FaresAbuIram commented on app/api/routes/user.py
> +def update_user(user_id: str, updated_user: User):
The user can't change others info

2024-10-15 06:56 UTC, FaresAbuIram commented on app/api/routes/user.py
You don't use the Depends and the token!!!!

2024-10-15 06:56 UTC, FaresAbuIram commented on app/api/routes/product.py
Where is the token !!!

2024-10-15 06:56 UTC, FaresAbuIram commented on .gitattributes
Why do you need this?

2024-10-15 06:56 UTC, FaresAbuIram commented on app/main.py
> -app.include_router(api_router, prefix="/api/v1")
Why do you remove this one? All routes should start with /api/vi

2024-10-15 15:12 UTC, closed without merging